name: 'connector_name'
version: '0.2.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
models:
  connector:
    +schema: stg_connector_name
    +materialized: table
vars:
  connector:
    table_name: "{{ ref('stg_connector__table_name') }}"
  connector_source:
    table_name: "{{ source('connector', 'table_name') }}"